### PR TITLE
Smaller image

### PR DESCRIPTION
**Pull request by raphaelauv**
(Thanks for your dockerfile, way nicer than mine)

I have a proposition : with a JRE the image is way more smaller ( 1.1GB -> 860MB )

### CODE REVIEW

**Comment by raphaelauv** [comment]
using 
```dockerfile
FROM eclipse-temurin:11-jre-alpine
```
give an image of 762MB

**Comment by raphaelauv** [comment]
the alpine image gave me problems with parquet and Unicode

it's better to use 

```Dockerfile
FROM eclipse-temurin:11-jre-focal
```

**Comment by raphaelauv** [comment]
@ykursadkaya ?

**Comment by ykursadkaya** [comment]
Oh so sorry, this must have been slipped my notice.

It is okay for me to change from JDK to JRE and use another base image, for the sake of a smaller image.

> the alpine image gave me problems with parquet and Unicode

I have another image that uses `bash:alpine` image for the base. Can you try this Docker file with your setup and see if you got any errors like this?

```Dockerfile
FROM bash:5.1.16-alpine3.15

RUN apk update
RUN apk add python3=3.9.7-r4 \
	py3-pip=20.3.4-r1 \
	openjdk11-jre-headless=11.0.14_p9-r0

RUN pip --no-cache-dir install pyspark==3.2.1

ENTRYPOINT ["python3"]
```

This Dockerfile results in 555 MB, but I could only tried creating SparkSession and nothing else.

**Comment by raphaelauv** [comment]
> Oh so sorry, this must have been slipped my notice.
> 
> It is okay for me to change from JDK to JRE and use another base image, for the sake of a smaller image.
> 
> > the alpine image gave me problems with parquet and Unicode
> 
> I have another image that uses `bash:alpine` image for the base. Can you try this Docker file with your setup and see if you got any errors like this?
> 
> ```dockerfile
> FROM bash:5.1.16-alpine3.15
> 
> RUN apk update
> RUN apk add python3=3.9.7-r4 \
> 	py3-pip=20.3.4-r1 \
> 	openjdk11-jre-headless=11.0.14_p9-r0
> 
> RUN pip --no-cache-dir install pyspark==3.2.1
> 
> ENTRYPOINT ["python3"]
> ```
> 
> This Dockerfile results in 555 MB, but I could only tried creating SparkSession and nothing else.

This image do not work if I replace `pyspark==3.2.1` by `pyspark[sql]==3.2.1`

numpy and pandas can't install

**Pull request closed without merging**
